# Generated by Django 5.0.6 on 2026-06-29 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='currency',
            field=models.CharField(choices=[('INR', 'INR'), ('USD', 'USD')], default='INR', max_length=3),
        ),
        migrations.AlterField(
            model_name='session',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
