# Generated by Django 5.0.6 on 2026-06-29 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_app', '0002_alter_session_currency_alter_session_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='age_restriction',
            field=models.CharField(choices=[('all_ages', 'All ages'), ('13+', '13+'), ('16+', '16+'), ('18+', '18+'), ('21+', '21+')], default='all_ages', max_length=10),
        ),
        migrations.AddField(
            model_name='session',
            name='agenda',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='session',
            name='cancellation_policy',
            field=models.CharField(choices=[('flexible', 'Flexible'), ('moderate', 'Moderate'), ('strict', 'Strict')], default='flexible', max_length=10),
        ),
        migrations.AddField(
            model_name='session',
            name='faqs',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='session',
            name='full_address',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='session',
            name='language',
            field=models.CharField(default='English', max_length=50),
        ),
        migrations.AddField(
            model_name='session',
            name='skill_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=15),
        ),
        migrations.AddField(
            model_name='session',
            name='venue_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='session',
            name='what_to_bring',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='session',
            name='what_you_will_learn',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='session',
            name='whats_included',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
